/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

/*
 * File: /System/Library/Frameworks/ScreenSaver.framework/Versions/A/ScreenSaver
 * Arch: Intel 80x86 (i386)
 *       Current version: 1.0.0, Compatibility version: 1.0.0
 */

@protocol ScreenSaverControl
- (BOOL)screenSaverIsRunning;
- (BOOL)screenSaverCanRun;
- (void)setScreenSaverCanRun:(BOOL)fp8;
- (void)screenSaverStartNow;
- (void)screenSaverStopNow;
- (void)restartForUser:(id)fp8;
- (double)screenSaverTimeRemaining;
- (void)screenSaverDidFade;
- (BOOL)screenSaverIsRunningInBackground;
- (void)screenSaverDidFadeInBackground:(BOOL)fp8 psnHi:(unsigned int)fp12 psnLow:(unsigned int)fp16;
@end

@interface ScreenSaverClockView : NSView
{
    int _alignment;
}



+ (unsigned int)backingStoreType;
+ (BOOL)performGammaFadeForModuleWithPath:(id)fp8;
+ (BOOL)performGammaFade;
+ (BOOL)spansScreens;
- (id)initWithFrame:(struct _NSRect)fp8;
- (id)initWithFrame:(struct _NSRect)fp8 isPreview:(BOOL)fp24;
- (void)dealloc;
- (double)animationTimeInterval;
- (void)setAnimationTimeInterval:(double)fp8;
- (void)startAnimation;
- (void)stopAnimation;
- (void)_resetTimer;
- (BOOL)isAnimating;
- (struct _NSRect)boundsInPixels;
- (BOOL)windowFlushEnabled;
- (void)_oneStep:(id)fp8;
- (void)animateOneFrame;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)hasConfigureSheet;
- (id)configureSheet;
- (BOOL)isPreview;

@end

@interface ScreenSaverModules : NSObject
{
    NSMutableDictionary *_modules;
    NSMutableDictionary *_times;
    unsigned int _searchDomains;
    NSMutableArray *_sortedModuleNames;
    NSString *_masterIPhotoAlbumName;



    int _indexOfFirstAppleModule;
    int _indexOfLastAppleModule;
    int _indexOfChooseFolderItem;
    int _indexOfDotMacModule;
    int _indexOfPicturesFolderModule;
    int _indexOfUserSelectedFolderItem;
    int _indexOfRSSModule;
    int _indexOfFirstIPhotoAlbumModule;
    int _indexOfLastIPhotoAlbumModule;
    int _indexOfIPhotoLibraryAlbumModule;
    int _indexOfFirstApertureProject;
    int _indexOfLastApertureProject;
    int _indexOfApertureLibrary;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (unsigned int)moduleSearchDomains;
- (void)setModuleSearchDomains:(unsigned int)fp8;
- (id)_directoriesInSearchDomain;
- (void)findModulesWithOrder:(id)fp8 forceRebuild:(BOOL)fp12;
- (BOOL)modulePathIsIPhotoAlbum:(id)fp8;
- (BOOL)modulePathIsMasterIPhotoAlbum:(id)fp8;
- (BOOL)modulePathIsApertureProject:(id)fp8;
- (BOOL)modulePathIsApertureLibrary:(id)fp8;
- (BOOL)modulePathIsPictureModule:(id)fp8;
- (BOOL)modulePathIsAppleModule:(id)fp8;
- (BOOL)modulePathIsDotMacSlides:(id)fp8;
- (BOOL)modulePathIsRSSPictures:(id)fp8;
- (int)indexOfFirstAppleModule;
- (int)indexOfLastAppleModule;
- (int)indexOfChooseFolderItem;
- (int)indexOfDotMacModule;
- (int)indexOfPicturesFolderModule;
- (int)indexOfRSSModule;
- (int)indexOfUserSelectedFolderItem;
- (int)indexOfFirstIPhotoAlbumModule;
- (int)indexOfLastIPhotoAlbumModule;
- (int)indexOfIPhotoLibraryAlbumModule;
- (int)indexOfFirstApertureProject;
- (int)indexOfLastApertureProject;
- (int)indexOfApertureLibrary;
- (id)basicModuleName;
- (id)basicModule;
- (id)slideShowModuleName;
- (id)moduleNames;
- (id)sortedModuleNamesForType:(id)fp8;
- (id)pathForModuleName:(id)fp8;
- (id)trueModuleNameForName:(id)fp8;
- (id)pathToLastUserSelectedFolder;
- (void)setUserSelectedFolderName:(id)fp8;
- (void)removeUserSelectedFolder;
- (Class)classForModuleWithName:(id)fp8;
- (Class)classForModuleWithPath:(id)fp8;
- (id)loadModuleWithName:(id)fp8;
- (id)loadModuleWithName:(id)fp8 frame:(struct _NSRect)fp12 isPreview:(BOOL)fp28;
- (id)loadModuleWithPath:(id)fp8;
- (id)loadModuleWithPath:(id)fp8 frame:(struct _NSRect)fp12 isPreview:(BOOL)fp28;
- (int)browser:(id)fp8 numberOfRowsInColumn:(int)fp12;
- (void)browser:(id)fp8 willDisplayCell:(id)fp12 atRow:(int)fp16 column:(int)fp20;
- (BOOL)browser:(id)fp8 selectRow:(int)fp12 inColumn:(int)fp16;
- (void)_checkIPhotoLoading;
- (void)_finishIPhotoLoading;
- (void)_checkApertureLoading;
- (void)_finishApertureLoading;

@end

@interface ScreenSaverDefaults : NSUserDefaults
{
    NSMutableDictionary *_defaults;
    NSMutableDictionary *_registeredDefaults;
    NSString *_userName;
    NSString *_domainName;
    BOOL _dirty;
    BOOL _screenLockPrefChanged;
}

+ (id)defaultsForUser:(id)fp8 moduleName:(id)fp12;
+ (id)defaultsForEngine;
+ (id)defaultsForModule:(id)fp8;
+ (id)defaultsForModuleWithName:(id)fp8;
+ (id)standardUserDefaults;
+ (void)resetStandardUserDefaults;
- (id)initWithUser:(id)fp8 moduleName:(id)fp12;
- (void)dealloc;
- (id)objectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (void)removeObjectForKey:(id)fp8;
- (void)registerDefaults:(id)fp8;
- (id)dictionaryRepresentation;
- (BOOL)synchronize;
- (BOOL)reload;
- (id)volatileDomainNames;
- (id)volatileDomainForName:(id)fp8;
- (void)setVolatileDomain:(id)fp8 forName:(id)fp12;
- (void)removeVolatileDomainForName:(id)fp8;
- (id)persistentDomainNames;
- (id)persistentDomainForName:(id)fp8;
- (void)setPersistentDomain:(id)fp8 forName:(id)fp12;
- (void)removePersistentDomainForName:(id)fp8;
- (id)description;

@end

@interface ScreenSaverDefaultsManager : NSObject
{
    NSMutableDictionary *_cache;
}

+ (id)defaultsManager;
- (id)init;
- (id)defaultsForKey:(id)fp8;
- (void)setDefaults:(id)fp8 forKey:(id)fp12;
- (void)synchronize;
- (void)_appWillTerminate:(id)fp8;

@end

@interface ScreenSaverUserInfo : NSObject
{
    unsigned int _eventHandle;
}

+ (id)sharedInstance;
- (id)init;
- (void)loginUserName:(id *)fp8 andID:(unsigned int *)fp12;
- (unsigned int)uidForUserName:(id)fp8;
- (double)idleTime;

@end

@interface ScreenSaverWindow : NSWindow
{
    NSMutableArray *_trectTags;
}

- (id)initWithContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 backing:(unsigned int)fp28 defer:(BOOL)fp32;
- (BOOL)canBecomeKeyWindow;
- (BOOL)canBecomeMainWindow;
- (void)startAnimating;
- (void)stopAnimating;
- (int)_setTrackingRect:(struct _NSRect)fp8 inside:(BOOL)fp24 owner:(id)fp28 userData:(void *)fp32 useTrackingNum:(int)fp36;
- (void)_discardTrackingRect:(int)fp8;
- (void)removeAllTrackingRects;
- (void)_cancelKey:(id)fp8;

@end

@interface ScreenSaverController : NSObject <ScreenSaverControl>
{
    NSConnection *_connection;
    id _daemonProxy;
    void *_reserved;
}

+ (id)controller;
+ (id)monitor;
+ (id)daemonConnectionName;
+ (id)enginePath;
- (void)_connectionClosed:(id)fp8;
- (id)init;
- (void)dealloc;
- (BOOL)screenSaverIsRunning;
- (BOOL)screenSaverCanRun;
- (void)setScreenSaverCanRun:(BOOL)fp8;
- (void)screenSaverStartNow;
- (void)screenSaverStopNow;
- (void)restartForUser:(id)fp8;
- (double)screenSaverTimeRemaining;
- (void)screenSaverDidFade;
- (BOOL)screenSaverIsRunningInBackground;
- (void)screenSaverDidFadeInBackground:(BOOL)fp8 psnHi:(unsigned int)fp12 psnLow:(unsigned int)fp16;

@end

@interface ScreenSaverEngine : NSResponder
{
    NSMutableArray *_windows;
    NSString *_moduleName;
    BOOL _debug;
    BOOL _debugLogging;
    BOOL _background;
    BOOL _mainOnly;
    BOOL _isRunning;
    BOOL _runFromPref;
    BOOL _blackSaver;
    BOOL _lockCountdown;
    int _retCode;
    struct _NSRect _mouseAllowedRect;
    struct _NSPoint _startingMousePoint;
    BOOL _keyEventTerminated;
    float _screenLockDelay;
    BOOL _performGammaFade;

    int _cornerListCnt;
    id _delegate;
}

- (id)init;
- (void)dealloc;
- (void)applicationDidFinishLaunching:(id)fp8;
- (int)_stateForMousePosition:(struct CGPoint)fp8 mask:(unsigned int)fp16;
- (void)_setupCornerShapes;
- (id)_makeWindowForSaver:(id)fp8 frame:(struct _NSRect)fp12 backingStoreType:(unsigned int)fp28;
- (void)_cancelKey:(id)fp8;
- (void)_resetTrackingRects;
- (void)_timedHideCursor;
- (void)applicationWillTerminate:(id)fp8;
- (void)applicationDidResignActive:(id)fp8;
- (void)startScreenSaver:(BOOL)fp8;
- (void)stopScreenSaver:(id)fp8;
- (void)pauseScreenSaver;
- (void)unpauseScreenSaver;
- (void)readjustDisplays;
- (BOOL)isBackground;
- (int)retCode;
- (void)setRunFromPref:(BOOL)fp8;
- (void)setDelegate:(id)fp8;
- (BOOL)isRunning;
- (void)keyDown:(id)fp8;
- (void)flagsChanged:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)mouseMoved:(id)fp8;
- (void)rightMouseUp:(id)fp8;
- (void)scrollWheel:(id)fp8;
- (void)tabletPoint:(id)fp8;
- (void)beginGestureWithEvent:(id)fp8;
- (void)swipeWithEvent:(id)fp8;

@end

@interface ScreenSaverClockWindow : NSWindow
{
    ScreenSaverClockView *_clockView;
    NSTimer *_updateTimer;
    NSBezierPath *_clockPath;
    struct _NSPoint _startingPoint;
    int _corner;
    int _lastHour;
    int _lastMinute;
    int _zeroPointIndex;
}

+ (void)show;
+ (void)hide;
- (void)dealloc;
- (id)initWithContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 backing:(unsigned int)fp28 defer:(BOOL)fp32;
- (void)_show;
- (void)_hide;
- (void)_constructClockPath;
- (int)_zeroPointIndexIntoClockPath;
- (void)_updateWindow;
- (void)_advanceClockPath:(id)fp8;
- (void)_advanceCorner;
- (void)_advanceHour;

@end




@interface ScreenSaverLockWindow : NSWindow
{

    NSTimer *_updateTimer;
    NSTimer *_fadeTimer;
    NSDate *_fadeStartTime;
    NSDate *_startTime;

}

+ (void)showWithCoountdownSeconds:(float)fp8;
+ (void)dismiss;
- (void)dealloc;
- (id)initWithContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 backing:(unsigned int)fp28 defer:(BOOL)fp32;
- (void)_dismiss;
- (void)_showWithCountdownSeconds:(float)fp8;
- (void)_updateWindow;
- (void)_fadeWindow;

@end

@interface ScreenSaverLockView : NSView
{
}

+ (id)bezierPathWithRoundRectInRect:(struct _NSRect)fp8 radius:(float)fp24;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;

@end

@interface ScreenSaverModule : NSObject
{
    NSString *_moduleName;
    NSString *_displayName;
    NSString *_path;
    NSString *_saverName;
    id _representedObject;
    BOOL _locNameLookupFlag;
}

+ (id)localizedSaverNameForPath:(id)fp8;
+ (id)moduleWithPath:(id)fp8;
+ (id)moduleWithName:(id)fp8;
+ (id)userSelectedPictureFolderAtPath:(id)fp8;
+ (id)picturesFolderModule;
- (void)dealloc;
- (BOOL)isScreenSaver;
- (BOOL)isSlideshow;
- (BOOL)isQC;
- (BOOL)isUserSelectedPicturesFolder;
- (id)name;
- (void)setName:(id)fp8;
- (id)displayName;
- (void)setDisplayName:(id)fp8;
- (id)path;
- (void)setPath:(id)fp8;
- (id)saverName;
- (void)setSaverName:(id)fp8;
- (id)representedObject;
- (void)setRepresentedObject:(id)fp8;
- (id)description;

@end


